#!/usr/bin/env node
'use strict';

/*
 * This script normalizes all the specs in examples/specs and
 * writes the full normalized spec to `examples/specs/normalized`
 * the normalized spec is different than the original.
 * We output this to a different folder so that build-examples script does not generate
 * redundant Vega output specs.
 */

const fs = require('fs'),
  vl = require('../build/src/index.js'),
  stringify = require('json-stable-stringify');

const DIR = __dirname + '/..';
const SPECS = '/examples/specs';
const examples = fs.readdirSync(DIR + SPECS);

examples.forEach(function(example) {
  if (example && example.includes('.vl.json')) {
    const path = DIR + SPECS + '/' + example;
    const file = JSON.parse(fs.readFileSync(path));

    const preNormalized = stringify(file);
    const fullSpec = vl.spec.normalize(file, vl.config.defaultConfig);
    const postNormalized = stringify(fullSpec);

    if (preNormalized !== postNormalized) {
      const postNormalizedOutput = JSON.stringify(fullSpec, null, 2);
      // -8 is cutting .vl.json
      const newFilename = example.slice(0, -8) + '_normalized.vl.json';
      const newFilenameAndPath = DIR + SPECS + '/normalized/' + newFilename;
      fs.writeFile(newFilenameAndPath, postNormalizedOutput, function(err) {
        if (err) return console.log(err);
        console.log("Built:", newFilename);
      });
    }
  }
});
