#!/usr/bin/env node

/**
 * This script creates pages for all examples for the website.
 */

import fs from "fs";
import examples from "../site/_data/examples.json" with { type: "json" };

function createPage(example) {
  return `---
layout: page
${example.description ? `description: "${example.description.replace(/"/g, '\\"')}"` : ""}
title: ${example.title}
menu: examples
permalink: /examples/${example.name}.html
image: /examples/${example.name}.png
edit_path: _data/examples.json
---

${example.description || ""}

{% include example.html spec='${example.name}'%}
`;
}

for (const category of Object.keys(examples)) {
  for (const subcategory of Object.keys(examples[category])) {
    for (const example of examples[category][subcategory]) {
      const name = example.name;

      console.log("Processing", name);

      const fileContent = fs.readFileSync(`examples/specs/${name}.vl.json`);

      if (!example.description) {
        const parsed = JSON.parse(fileContent);
        example.description = parsed.description;
      }

      fs.writeFileSync(`site/examples/${name}.md`, createPage(example));
    }
  }
}
