#!/usr/bin/env node
'use strict';

/**
 * This script creates pages for all examples for the website.
 */

const fs = require('fs');
const examples = require('../_data/examples.json');
const { execSync } = require('child_process');
const { createConverter } = require('convert-svg-to-png');

function createPage(example) {
  return (`---
layout: page
menu: examples
${example.description ? `description: ${example.description}`: ''}
title: ${example.title}
permalink: /examples/${example.name}.html
image: /examples/compiled/${example.name}.png
---

${example.description || ''}

{% include example.html spec='${example.name}'%}
`);
}

const converter = createConverter();

const run = async () => {
  try {
    for (const category of Object.keys(examples)) {
      for (const example of examples[category]) {
        const name = example.name;

        console.log(`Processing ${name}`);

        fs.writeFileSync(`site/examples/${name}.vl.json`, fs.readFileSync(`examples/specs/${name}.vl.json`));
        fs.writeFileSync(`site/examples/${name}.md`, createPage(example));
        const svg = fs.readFileSync(`examples/compiled/${name}.svg`);
        const output = await converter.convert(svg);
        fs.writeFileSync(`examples/compiled/${name}.png`, output);
      }
    }
  } finally {
    await converter.destroy();
  }
}

run();
