#!/usr/bin/env node
'use strict';

var fs = require('fs'),
  path = require('path');

var DIR = __dirname + '/..';
var SPECS = '/examples/specs';
var OUTPUT = '/examples/all-examples.json';

var examples = fs.readdirSync(DIR + SPECS);

var examples = examples.filter(function(example) {
  return path.extname(example) === '.json'
}).map(function(example){
  return path.basename(example, '.vl.json');
})

fs.writeFile(DIR + OUTPUT, JSON.stringify(examples), function (err) {
  if (err) return console.log(err);
  console.log('Indexed all examples [source: ' + SPECS + ', index: ' + OUTPUT + ']');
});
