perl -pi -e s,'<Field>','',g build/vega-lite-schema.json
perl -pi -e s,'FacetedCompositeUnitSpec','FacetedUnitSpec',g build/vega-lite-schema.json
perl -pi -e s,'GenericLayerSpec<CompositeUnitSpec>','LayerSpec',g build/vega-lite-schema.json
perl -pi -e s,'GenericFacetSpec<CompositeUnitSpec>','FacetedSpec',g build/vega-lite-schema.json
perl -pi -e s,'GenericRepeatSpec<CompositeUnitSpec>','RepeatSpec',g build/vega-lite-schema.json
perl -pi -e s,'GenericVConcatSpec<CompositeUnitSpec>','VConcatSpec',g build/vega-lite-schema.json
perl -pi -e s,'GenericHConcatSpec<CompositeUnitSpec>','HConcatSpec',g build/vega-lite-schema.json
perl -pi -e s,'GenericUnitSpec<EncodingWithFacet\,AnyMark>','FacetedCompositeUnitSpecAlias',g build/vega-lite-schema.json
perl -pi -e s,'GenericUnitSpec<Encoding\,AnyMark>','CompositeUnitSpecAlias',g build/vega-lite-schema.json
perl -pi -e s,'LogicalOperand<string>','LogicalOperand',g build/vega-lite-schema.json
perl -pi -e s,'LogicalAnd<string>','LogicalAnd',g build/vega-lite-schema.json
perl -pi -e s,'LogicalOr<string>','LogicalOr',g build/vega-lite-schema.json
perl -pi -e s,'LogicalNot<string>','LogicalNot',g build/vega-lite-schema.json
perl -pi -e s,'LogicalOperand<Filter>','FilterOperand',g build/vega-lite-schema.json
perl -pi -e s,'LogicalAnd<Filter>','AndFilter',g build/vega-lite-schema.json
perl -pi -e s,'LogicalOr<Filter>','OrFilter',g build/vega-lite-schema.json
perl -pi -e s,'LogicalNot<Filter>','NotFilter',g build/vega-lite-schema.json
