var SUMMARY = 'summary'
var SOURCE = 'source'
var STACKED = 'stacked'
var INDEX = 'index'

var X = 'x'
var Y = 'y'
var ROW = 'row'
var COL = 'col'
var SIZE = 'size'
var SHAPE = 'shape'
var COLOR = 'color'
var TEXT = 'text'
var DETAIL = 'detail'

var N = 'N'
var O = 'O'
var Q = 'Q'
var T = 'T'
