const SUMMARY = 'summary'
const SOURCE = 'source'
const STACKED = 'stacked'
const INDEX = 'index'

const X = 'x'
const Y = 'y'
const ROW = 'row'
const COL = 'col'
const SIZE = 'size'
const SHAPE = 'shape'
const COLOR = 'color'
const TEXT = 'text'
const DETAIL = 'detail'

const N = 'N'
const O = 'O'
const Q = 'Q'
const T = 'T'
